# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'sales_aggregationWgLYEI.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

import os
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

script_directory = os.path.dirname(os.path.realpath(__file__))

class Ui_MainWindow(object):
    def __init__(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1100, 580)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(1100, 580))
        MainWindow.setMaximumSize(QSize(1100, 580))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(115, 115, 115, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Button, brush1)
        palette.setBrush(QPalette.Active, QPalette.Light, brush)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush2 = QBrush(QColor(51, 51, 51, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Base, brush2)
        brush3 = QBrush(QColor(42, 42, 42, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Window, brush3)
        brush4 = QBrush(QColor(85, 0, 255, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ToolTipText, brush4)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Button, brush1)
        palette.setBrush(QPalette.Inactive, QPalette.Light, brush)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.Base, brush2)
        palette.setBrush(QPalette.Inactive, QPalette.Window, brush3)
        palette.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush4)
        brush5 = QBrush(QColor(120, 120, 120, 255))
        brush5.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Button, brush1)
        palette.setBrush(QPalette.Disabled, QPalette.Light, brush)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush5)
        palette.setBrush(QPalette.Disabled, QPalette.Base, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.Window, brush3)
        palette.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush4)
        MainWindow.setPalette(palette)
        font = QFont()
        font.setFamily(u"Raleway Medium")
        font.setPointSize(7)
        MainWindow.setFont(font)
        MainWindow.setAutoFillBackground(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QTabWidget.Triangular)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(30, 30, 201, 511))
        palette1 = QPalette()
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Active, QPalette.Text, brush)
        brush6 = QBrush(QColor(170, 85, 255, 255))
        brush6.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Base, brush6)
        brush7 = QBrush(QColor(18, 18, 18, 255))
        brush7.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette1.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        brush8 = QBrush(QColor(255, 255, 255, 128))
        brush8.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette1.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette1.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette1.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette1.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.Window, brush7)
        palette1.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        brush9 = QBrush(QColor(0, 0, 0, 128))
        brush9.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
        self.groupBox.setPalette(palette1)
        font1 = QFont()
        font1.setFamily(u"Raleway Medium")
        font1.setPointSize(11)
        font1.setBold(True)
        font1.setItalic(False)
        font1.setWeight(75)
        font1.setStyleStrategy(QFont.PreferAntialias)
        self.groupBox.setFont(font1)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(20, 50, 161, 36))
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush10 = QBrush(QColor(0, 172, 193, 255))
        brush10.setStyle(Qt.SolidPattern)
        palette2.setBrush(QPalette.Active, QPalette.Button, brush10)
        palette2.setBrush(QPalette.Active, QPalette.Text, brush)
        palette2.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Active, QPalette.Base, brush10)
        palette2.setBrush(QPalette.Active, QPalette.Window, brush10)
        brush11 = QBrush(QColor(255, 255, 255, 128))
        brush11.setStyle(Qt.NoBrush)
        palette2.setBrush(QPalette.Active, QPalette.PlaceholderText, brush11)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette2.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.Base, brush10)
        palette2.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        brush12 = QBrush(QColor(255, 255, 255, 128))
        brush12.setStyle(Qt.NoBrush)
        palette2.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush12)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        palette2.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette2.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        brush13 = QBrush(QColor(255, 255, 255, 128))
        brush13.setStyle(Qt.NoBrush)
        palette2.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush13)
        self.pushButton.setPalette(palette2)
        font2 = QFont()
        font2.setFamily(u"Quicksand SemiBold")
        font2.setPointSize(11)
        font2.setBold(True)
        font2.setUnderline(False)
        font2.setWeight(62)
        font2.setStrikeOut(False)
        font2.setKerning(True)
        font2.setStyleStrategy(QFont.PreferAntialias)
        self.pushButton.setFont(font2)
        self.pushButton.setAutoFillBackground(False)
        self.pushButton.setStyleSheet(u"outline: 0px;\n""border: 0px;\n""text-decoration: none;\n""font-weight: 500;\n""text-transform: uppercase;\n""letter-spacing: 0.1px;\n""padding: 6px 16px;\n""color: rgb(255, 255, 255);\n""background-color: #00acc1;")
        icon = QIcon()
        icon.addFile(f"{script_directory}/icons/login.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QSize(20, 20))
        self.pushButton_2 = QPushButton(self.groupBox)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(20, 110, 161, 36))
        palette3 = QPalette()
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Button, brush10)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush)
        palette3.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Active, QPalette.Base, brush10)
        palette3.setBrush(QPalette.Active, QPalette.Window, brush10)
        brush14 = QBrush(QColor(255, 255, 255, 128))
        brush14.setStyle(Qt.NoBrush)
        palette3.setBrush(QPalette.Active, QPalette.PlaceholderText, brush14)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Inactive, QPalette.Base, brush10)
        palette3.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        brush15 = QBrush(QColor(255, 255, 255, 128))
        brush15.setStyle(Qt.NoBrush)
        palette3.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush15)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette3.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette3.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        brush16 = QBrush(QColor(255, 255, 255, 128))
        brush16.setStyle(Qt.NoBrush)
        palette3.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush16)
        self.pushButton_2.setPalette(palette3)
        font3 = QFont()
        font3.setFamily(u"Quicksand SemiBold")
        font3.setPointSize(11)
        font3.setBold(True)
        font3.setItalic(False)
        font3.setUnderline(False)
        font3.setWeight(62)
        font3.setStrikeOut(False)
        font3.setKerning(True)
        font3.setStyleStrategy(QFont.PreferAntialias)
        self.pushButton_2.setFont(font3)
        self.pushButton_2.setAutoFillBackground(False)
        self.pushButton_2.setStyleSheet(u"outline: 0px;\n""border: 0px;\n""text-decoration: none;\n""font-weight: 500;\n""text-transform: uppercase;\n""letter-spacing: 0.1px;\n""padding: 6px 16px;\n""color: rgb(255, 255, 255);\n""background-color: #00acc1;")
        icon1 = QIcon()
        icon1.addFile(f"{script_directory}/icons/text-file.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QSize(20, 20))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(80, 480, 47, 13))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(270, 30, 541, 511))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush)
        palette4.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette4.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette4.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette4.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette4.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette4.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette4.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette4.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.Window, brush7)
        palette4.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        palette4.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
        self.groupBox_2.setPalette(palette4)
        self.groupBox_2.setFont(font1)
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setStyleSheet(u"border: 1px solid;border-color: #6d6d6d;")
        self.groupBox_2.setFlat(False)
        self.groupBox_2.setCheckable(False)
        self.plainTextEdit = QTextEdit(self.groupBox_2)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(10, 50, 521, 401))
        font4 = QFont()
        font4.setFamily(u"Roboto")
        font4.setPointSize(10)
        font4.setBold(False)
        font4.setItalic(False)
        font4.setWeight(50)
        font4.setStyleStrategy(QFont.PreferDefault)
        self.plainTextEdit.setFont(font4)
        self.plainTextEdit.setReadOnly(True)
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setStyleSheet(u"background:#212121;color:#FFFFFF;border: 1px solid;border-color: #6d6d6d;")
        self.plainTextEdit.setFrameShape(QFrame.Box)
        self.plainTextEdit.setFrameShadow(QFrame.Plain)
        # self.plainTextEdit.setTextInteractionFlags(Qt.TextEditorInteraction)
        # self.plainTextEdit.setBackgroundVisible(True)
        self.progressBar = QProgressBar(self.groupBox_2)
        self.progressBar.setObjectName(u"progressBar")
        self.progressBar.setGeometry(QRect(10, 472, 521, 21))
        font5 = QFont()
        font5.setFamily(u"Times New Roman")
        font5.setPointSize(11)
        self.progressBar.setFont(font5)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet(u"color:#000;background:#2a2a2a;")
        self.progressBar.setValue(0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QProgressBar.TopToBottom)
        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(850, 20, 211, 431))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush)
        palette5.setBrush(QPalette.Active, QPalette.Base, brush6)
        palette5.setBrush(QPalette.Active, QPalette.Window, brush7)
        palette5.setBrush(QPalette.Active, QPalette.ToolTipText, brush)
        palette5.setBrush(QPalette.Active, QPalette.PlaceholderText, brush8)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.Base, brush6)
        palette5.setBrush(QPalette.Inactive, QPalette.Window, brush7)
        palette5.setBrush(QPalette.Inactive, QPalette.ToolTipText, brush)
        palette5.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush8)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush5)
        palette5.setBrush(QPalette.Disabled, QPalette.Base, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.Window, brush7)
        palette5.setBrush(QPalette.Disabled, QPalette.ToolTipText, brush)
        palette5.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush9)
        self.groupBox_3.setPalette(palette5)
        self.groupBox_3.setFont(font1)
        self.groupBox_3.setAutoFillBackground(False)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setCheckable(False)
        self.formLayoutWidget = QWidget(self.groupBox_3)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(10, 60, 196, 331))
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setLabelAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.formLayout.setFormAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.formLayout.setHorizontalSpacing(4)
        self.formLayout.setVerticalSpacing(6)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.cb_get_sales_from_icg = QCheckBox(self.formLayoutWidget)
        self.cb_get_sales_from_icg.setObjectName(u"cb_get_sales_from_icg")
        font6 = QFont()
        font6.setFamily(u"Quicksand SemiBold")
        font6.setPointSize(10)
        font6.setBold(False)
        font6.setItalic(False)
        font6.setWeight(50)
        font6.setStyleStrategy(QFont.PreferAntialias)
        self.cb_get_sales_from_icg.setFont(font6)
        self.cb_get_sales_from_icg.setChecked(True)

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.cb_get_sales_from_icg)

        self.cb_use_only_active_stores = QCheckBox(self.formLayoutWidget)
        self.cb_use_only_active_stores.setObjectName(u"cb_use_only_active_stores")
        self.cb_use_only_active_stores.setFont(font6)
        self.cb_use_only_active_stores.setChecked(True)

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.cb_use_only_active_stores)

        self.cb_save_records = QCheckBox(self.formLayoutWidget)
        self.cb_save_records.setObjectName(u"cb_save_records")
        self.cb_save_records.setFont(font6)
        self.cb_save_records.setChecked(False)

        self.formLayout.setWidget(2, QFormLayout.LabelRole, self.cb_save_records)

        self.cb_post_to_byd = QCheckBox(self.formLayoutWidget)
        self.cb_post_to_byd.setObjectName(u"cb_post_to_byd")
        self.cb_post_to_byd.setFont(font6)
        self.cb_post_to_byd.setChecked(False)

        self.formLayout.setWidget(3, QFormLayout.LabelRole, self.cb_post_to_byd)

        self.cb_use_todays_date = QCheckBox(self.formLayoutWidget)
        self.cb_use_todays_date.setObjectName(u"cb_use_todays_date")
        self.cb_use_todays_date.setFont(font6)
        self.cb_use_todays_date.setAutoFillBackground(False)
        self.cb_use_todays_date.setStyleSheet(u"color:#fff;")
        self.cb_use_todays_date.setChecked(True)

        self.formLayout.setWidget(4, QFormLayout.LabelRole, self.cb_use_todays_date)

        self.dateEdit = QDateEdit(self.formLayoutWidget)
        self.dateEdit.setObjectName(u"dateEdit")
        self.dateEdit.setEnabled(True)
        self.dateEdit.setDate(QDate.currentDate())
        font8 = QFont()
        font8.setFamily(u"Times New Roman")
        font8.setPointSize(13)
        font8.setBold(False)
        font8.setItalic(False)
        font8.setWeight(50)
        font8.setStyleStrategy(QFont.PreferDefault)
        self.dateEdit.setFont(font8)
        self.dateEdit.setStyleSheet(u"border: 1px solid;border-color: #6d6d6d;background:#2a2a2a;color:#FFF;")
        self.dateEdit.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.dateEdit.setProperty("showGroupSeparator", True)
        self.dateEdit.setCalendarPopup(True)

        self.formLayout.setWidget(5, QFormLayout.LabelRole, self.dateEdit)

        self.label_2 = QLabel(self.groupBox_3)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(80, 40, 51, 20))
        font9 = QFont()
        font9.setFamily(u"Quicksand Medium")
        font9.setPointSize(10)
        font9.setBold(True)
        font9.setItalic(False)
        font9.setWeight(75)
        font9.setStyleStrategy(QFont.PreferAntialias)
        self.label_2.setFont(font9)
        self.pushButton_8 = QPushButton(self.centralwidget)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(850, 480, 211, 61))
        palette6 = QPalette()
        palette6.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Button, brush10)
        palette6.setBrush(QPalette.Active, QPalette.Text, brush)
        palette6.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Active, QPalette.Base, brush10)
        palette6.setBrush(QPalette.Active, QPalette.Window, brush10)
        brush17 = QBrush(QColor(255, 255, 255, 128))
        brush17.setStyle(Qt.NoBrush)
        palette6.setBrush(QPalette.Active, QPalette.PlaceholderText, brush17)
        palette6.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Button, brush10)
        palette6.setBrush(QPalette.Inactive, QPalette.Text, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Inactive, QPalette.Base, brush10)
        palette6.setBrush(QPalette.Inactive, QPalette.Window, brush10)
        brush18 = QBrush(QColor(255, 255, 255, 128))
        brush18.setStyle(Qt.NoBrush)
        palette6.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush18)
        palette6.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Button, brush10)
        palette6.setBrush(QPalette.Disabled, QPalette.Text, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        palette6.setBrush(QPalette.Disabled, QPalette.Base, brush10)
        palette6.setBrush(QPalette.Disabled, QPalette.Window, brush10)
        brush19 = QBrush(QColor(255, 255, 255, 128))
        brush19.setStyle(Qt.NoBrush)
        palette6.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush19)
        self.pushButton_8.setPalette(palette6)
        font10 = QFont()
        font10.setFamily(u"Quicksand SemiBold")
        font10.setPointSize(16)
        font10.setBold(True)
        font10.setItalic(False)
        font10.setUnderline(False)
        font10.setWeight(62)
        font10.setStrikeOut(False)
        font10.setKerning(True)
        font10.setStyleStrategy(QFont.PreferAntialias)
        self.pushButton_8.setFont(font10)
        self.pushButton_8.setAutoFillBackground(False)
        self.pushButton_8.setStyleSheet(u"outline: 0px;\n""border: 0px;\n""text-decoration: none;\n""font-weight: 500;\n""text-transform: uppercase;\n""letter-spacing: 0.1px;\n""padding: 6px 16px;\n""color: rgb(255, 255, 255);\n""background-color: #00acc1;")
        icon3 = QIcon()
        icon3.addFile(f"{script_directory}/icons/play.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setIconSize(QSize(30, 30))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Sales Aggregation Service", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"QUICK ACTIONS", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Start Admin", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"OPEN LOG FILE", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"v0.0.1", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"PROCESS LOGS", None))
        self.plainTextEdit.setDocumentTitle("")
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"RUN", None))
        self.cb_get_sales_from_icg.setText(QCoreApplication.translate("MainWindow", u"Fetch From ICG", None))
        self.cb_use_only_active_stores.setText(QCoreApplication.translate("MainWindow", u"Use Only Active Stores", None))
        self.cb_save_records.setText(QCoreApplication.translate("MainWindow", u"Save Records", None))
        self.cb_post_to_byd.setText(QCoreApplication.translate("MainWindow", u"Create Journal Entries", None))
        self.cb_use_todays_date.setText(QCoreApplication.translate("MainWindow", u"Use Today's Date", None))
        self.dateEdit.setDisplayFormat(QCoreApplication.translate("MainWindow", u"yyyy/MM/dd", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Options", None))
        self.pushButton_8.setText(QCoreApplication.translate("MainWindow", u"EXECUTE", None))
    # retranslateUi