# Generated by Django 4.2.7 on 2023-11-16 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=255)),
                ('icg_warehouse_code', models.CharField(max_length=20, unique=True)),
                ('byd_cost_center_code', models.CharField(max_length=20, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('sales_tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('consumption_tax', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tourism_development_levy', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
    ]
