# Generated by Django 4.2.7 on 2023-11-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=5),
        ),
    ]
