# Generated by Django 4.2.7 on 2023-11-16 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0002_store_vat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_data', models.JSONField()),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('water_sales', models.DecimalField(decimal_places=2, max_digits=10)),
                ('staff_meal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_sale_after_water', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('vat_percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('consumption_tax_percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('tourism_development_levy_percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('vat', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('consumption_tax', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('tourism_development_levy', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('sales_tax', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('net_sales', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_services.store')),
            ],
        ),
    ]
