# Generated by Django 4.2.7 on 2023-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0003_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='post_sale_to_byd',
            field=models.BooleanField(default=True),
        ),
    ]
