# Generated by Django 4.2.7 on 2023-12-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0004_store_post_sale_to_byd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='consumption_tax',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='consumption_tax_percentage',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='gross_sale_after_water',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='net_sales',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sales_tax',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tourism_development_levy',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='tourism_development_levy_percentage',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='vat',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='vat_percentage',
        ),
        migrations.RemoveField(
            model_name='store',
            name='sales_tax',
        ),
        migrations.AddField(
            model_name='sales',
            name='calculated_sales_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='posted_to_byd',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sales',
            name='store_percentages',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='last_synced',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='locality_marketing_provision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='marketing_fund_provision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='mgmt_fee_development',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='mgmt_fee_hr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='mgmt_fee_share_service',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='variable_rent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='sales',
            name='water_sales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
