# Generated by Django 4.2.7 on 2023-12-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0005_remove_sales_consumption_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='mgmt_fee',
            field=models.DecimalField(decimal_places=2, default=0.075, max_digits=5),
        ),
        migrations.AlterField(
            model_name='store',
            name='mgmt_fee_development',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=5),
        ),
        migrations.AlterField(
            model_name='store',
            name='mgmt_fee_hr',
            field=models.DecimalField(decimal_places=2, default=23, max_digits=5),
        ),
        migrations.AlterField(
            model_name='store',
            name='mgmt_fee_share_service',
            field=models.DecimalField(decimal_places=2, default=62, max_digits=5),
        ),
    ]
