# Generated by Django 4.2.7 on 2023-12-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0006_store_mgmt_fee_alter_store_mgmt_fee_development_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='locality_marketing_provision',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='marketing_fund_provision',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='mgmt_fee',
            field=models.DecimalField(decimal_places=5, default=0.075, max_digits=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='mgmt_fee_development',
            field=models.DecimalField(decimal_places=5, default=15, max_digits=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='mgmt_fee_hr',
            field=models.DecimalField(decimal_places=5, default=23, max_digits=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='mgmt_fee_share_service',
            field=models.DecimalField(decimal_places=5, default=62, max_digits=10),
        ),
        migrations.AlterField(
            model_name='store',
            name='variable_rent',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
