# Generated by Django 4.2.7 on 2024-01-02 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0007_alter_store_locality_marketing_provision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(),
        ),
    ]
