# Generated by Django 4.2.7 on 2024-01-04 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0008_alter_sales_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='state',
        ),
        migrations.AddField(
            model_name='store',
            name='icg_warehouse_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
