# Generated by Django 4.2.7 on 2024-01-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0009_remove_store_state_store_icg_warehouse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='post_sale_to_byd',
            field=models.BooleanField(default=False),
        ),
    ]
