# Generated by Django 4.2.7 on 2024-01-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0010_alter_store_post_sale_to_byd'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='byd_account_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='byd_bill_to_party_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='byd_sales_unit_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
