# Generated by Django 4.2.7 on 2024-05-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0011_store_byd_account_id_store_byd_bill_to_party_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
