# Generated by Django 4.2.7 on 2024-08-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0012_store_store_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='byd_supplier_ck_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='byd_supplier_ppu_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='icg_future_warehouse_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
