# Generated by Django 4.2.7 on 2024-08-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0013_store_byd_supplier_ck_id_store_byd_supplier_ppu_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='byd_cost_center_code',
            field=models.CharField(max_length=20),
        ),
    ]
