# Generated by Django 4.2.7 on 2024-08-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_services', '0014_alter_store_byd_cost_center_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
