# Generated by Django 4.2.7 on 2024-08-13 18:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store_services', '0015_delete_sales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('canonical_name', models.CharField(blank=True, max_length=255, null=True)),
                ('byd_gl_code', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciled_gross_total', models.FloatField()),
                ('outstanding_gross_total', models.FloatField(default=0.0)),
                ('sale_date', models.DateField()),
                ('signature', models.TextField(unique=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('hash_digest', models.CharField(max_length=255)),
                ('store_percentages', models.JSONField()),
                ('calculated_sales_data', models.JSONField()),
                ('posted_to_byd', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_services.store')),
            ],
        ),
    ]
