# Generated by Django 4.2.7 on 2023-12-13 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_aggregation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledgeraccount',
            name='byd_cost_center_code',
        ),
    ]
